### ISSUE TITLE
Problème oauth2

### ISSUE THREAD

**Issue by grangerp** [MappedIn/platform-api#7]
Hi,
We are currently choosing a map provider and I try to test your service.
I already have my Key: 56781818ab0b3070e6000000 and my secret: xxxxxxxxx.

I have try to to use the oauth2 authentication (https://github.com/MappedIn/platform-api/blob/master/v1.md#authentication-and-authorization) but I am on the impression that https://auth.mappedin.com/oauth2/authorize return 302 and https://auth.mappedin.com/oauth2/token return 404.

Is this doc up to date?

Thanks

**Comment by ppaskaris** [comment]
The token endpoint will return a 404 if you make a GET request. You should be able to POST to it using the client_credentials grant:

```http
POST /oauth2/token HTTP/1.1
Accept: application/json
Content-Length: 88
Content-Type: application/x-www-form-urlencoded; charset=utf-8
Host: auth.mappedin.com

grant_type=client_credentials&client_id=56781818ab0b3070e6000000&client_secret=xxxxxxxxx
```
